# Generated by Django 3.1.5 on 2021-01-26 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='newsReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='title here')),
                ('Image', models.ImageField(default='good-news.jpg', upload_to='news_pics')),
                ('Date_created', models.DateField(auto_now_add=True)),
                ('Description', models.TextField(max_length=1000)),
                ('Place', models.CharField(max_length=100)),
                ('Tag', models.CharField(choices=[('academics', 'academics'), ('sports', 'sports'), ('entertainment', 'entertainment'), ('carrier', 'carrier'), ('business', 'business'), ('other', 'other')], max_length=50)),
                ('Status', models.BooleanField(default=False)),
                ('Views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='volunteerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('Image', models.ImageField(default='volunteer.png', upload_to='volunteer_pics')),
                ('Date_created', models.DateField(auto_now_add=True)),
                ('Introduction', models.CharField(blank=True, max_length=200, null=True)),
                ('Profession', models.CharField(blank=True, max_length=50, null=True)),
                ('Experience', models.CharField(blank=True, max_length=30, null=True)),
                ('PurposeOfLife', models.CharField(blank=True, max_length=100, null=True)),
                ('Hobbies', models.CharField(blank=True, max_length=50, null=True)),
                ('HideContactDetail', models.BooleanField(default=True)),
                ('volunteer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(blank=True, max_length=50, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('PurposeOfLife', models.CharField(blank=True, max_length=100, null=True)),
                ('Hobbies', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='newsViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hustlerApp.newsreport')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='newsLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hustlerApp.newsreport')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
